---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: jails.yml
  when: ssh_chroot_jail_enabled == true

- include_tasks: jail-user.yml
  when: ssh_chroot_jail_enabled == true
  
